### ISSUE TITLE
Use dicts for function parameters that represent Neo4j nodes

### ISSUE THREAD

**Issue by majensen** [nelsonwmoore/HIDS-Capstone#1]
Rather than thinking of a term as just its text value, better to think of a term as a dictionary that has 'value' as one of its keys. 
The reason is, a term is really a combination of its text value and its origin. So for example, checking if a term exists should be checking if there is a term node in the database with both a given value and a given origin. 

Rather than:
```
def check_term_exists(tx, term_val):
  result = tx.run("MATCH (t:term {value: $term_val}) "
                  "RETURN t.value AS term", term_val=term_val)
  if [record["term"] for record in result]:
    return True
  else:
    return False
```
do:
```
def check_term_exists(tx, term):
  if not ("origin_name" in term and "value" in term):
    raise RuntimeError("arg 'term' must contain both origin_name and value keys")    
  result = tx.run("MATCH (t:term {value: $term_val, origin_name:$term_origin}) "
                  "RETURN t.value AS term", term_val=term["value"], term_origin=term["origin_name"])
  if [record["term"] for record in result]:
    return True
  else:
    return False
```
Similarly across all the functions.

**Comment by nelsonwmoore** [comment]
Edited functions to use dicts rather than individual node properties

https://github.com/nelsonwmoore/HIDS-Capstone/pull/6
