### ISSUE TITLE
Use the 'nanoid' package

### ISSUE THREAD

**Issue by majensen** [nelsonwmoore/HIDS-Capstone#2]
There is a nanoid package out there that creates these in a standard way (probably really close to how you're doing it!). Best to use that since we use it elsewhere in the codebase. We also use a subset of the alphabet that avoids ambiguous chars (like 0 and O etc.)

```
from nanoid import generate
def make_nano():
    return generate(
        size=6,
        alphabet="abcdefghijkmnopqrstuvwxyzABCDEFGHJKMNPQRSTUVWXYZ0123456789"
    )
new_nanoid = make_nano()
```
Should be able to just 
```
pip install nanoid
```
to get it.

**Comment by nelsonwmoore** [comment]
Changed the nanoid generation function to use the nanoid package. I left the function that checks that the generated nanoid is unique for now; If I should just use the generated id only without checking uniqueness let me know and I'll fix that too!
